### ISSUE TITLE
Obscure error when `llvm-config` segfaults

### ISSUE THREAD

**Issue by alexcrichton** [KyleMayes/clang-sys#92]
I was working with a contributor today and the usage of `clang-sys` through the `bindgen` crate produced a very odd error that we couldnt figure out. When building the [wasmtime repository](https://github.com/cranestation/wasmtime) if `llvm-config` segfaulted we got a weird error like:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
```

It took some investigation to figure this out, but it turned out to be `llvm-config` segfaulting. I was able to reproduced this with:

```
$ cat llvm-config.rs
fn main() {                                                                                
    extern { fn abort(); }                         
    unsafe { abort(); }                    
}                                          
$ rustc llvm-config.rs
$ RUST_BACKTRACE=1 PATH=`pwd`:$PATH cargo build
...
```

<details>

<summary>Output</summary>

```
   Compiling wasmtime-runtime v0.1.0 (/Users/acrichton/code/wasmtime/wasmtime-runtime)
   Compiling wasmtime-wasi-c v0.0.0 (/Users/acrichton/code/wasmtime/wasmtime-wasi-c)
error: failed to run custom build command for `wasmtime-runtime v0.1.0 (/Users/acrichton/code/wasmtime/wasmtime-runtime)`
process didn't exit successfully: `/Users/acrichton/code/wasmtime/target/debug/build/wasmtime-runtime-3556dac70578d2fd/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/Users/acrichton/code/wasmtime/wasmtime-runtime/signalhandlers" "-DCMAKE_INSTALL_PREFIX=/Users/acrichton/code/wasmtime/target/debug/build/wasmtime-runtime-00c6ea1bb851df32/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/acrichton/code/wasmtime/target/debug/build/wasmtime-runtime-00c6ea1bb851df32/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--"
[100%] Built target SignalHandlers
Install the project...
-- Install configuration: "Debug"
-- Installing: /Users/acrichton/code/wasmtime/target/debug/build/wasmtime-runtime-00c6ea1bb851df32/out/./libSignalHandlers.a
cargo:root=/Users/acrichton/code/wasmtime/target/debug/build/wasmtime-runtime-00c6ea1bb851df32/out
cargo:rustc-link-search=native=/Users/acrichton/code/wasmtime/target/debug/build/wasmtime-runtime-00c6ea1bb851df32/out
cargo:rustc-link-lib=static=SignalHandlers

--- stderr
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:308
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:49
   9: alloc::slice::merge_sort::collapse
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/macros.rs:12
  10: clang_sys::load_manually::build::common::search_libclang_directories
             at /Users/acrichton/code/wasmtime/target/debug/build/clang-sys-c99eebbe3167a4ea/out/common.rs:120
  11: clang_sys::load_manually::build::dynamic::search_libclang_directories
             at /Users/acrichton/code/wasmtime/target/debug/build/clang-sys-c99eebbe3167a4ea/out/dynamic.rs:132
  12: clang_sys::load_manually::build::dynamic::find
             at /Users/acrichton/code/wasmtime/target/debug/build/clang-sys-c99eebbe3167a4ea/out/dynamic.rs:159
  13: clang_sys::clang_HTMLTagComment_getTagName::{{closure}}
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.0/src/link.rs:128
  14: clang_sys::load_manually::{{closure}}
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.0/src/link.rs:157
  15: core::ops::function::FnOnce::call_once
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.49.2/src/lib.rs:1688
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/ops/function.rs:231
  16: alloc::raw_vec::alloc_guard
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0/src/inline_lazy.rs:28
  17: std::sync::once::Once::is_completed
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/sync/once.rs:220
  18: std::sync::once::Once::call_once::{{closure}}
             at src/libstd/sync/once.rs:387
  19: std::sync::once::Once::is_completed
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/sync/once.rs:220
  20: bindgen::CodegenConfig::contains
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0/src/inline_lazy.rs:27
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.49.2/<::lazy_static::__lazy_static_internal macros>:12
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.49.2/<::lazy_static::__lazy_static_internal macros>:13
  21: bindgen::ensure_libclang_is_loaded
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.49.2/src/lib.rs:1695
  22: bindgen::Bindings::generate
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.49.2/src/lib.rs:1710
  23: bindgen::args_are_cpp::{{closure}}
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.49.2/src/lib.rs:1208
  24: build_script_build::main
             at wasmtime-runtime/build.rs:32
  25: std::rt::lang_start::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/rt.rs:64
  26: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  27: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:87
  28: std::panicking::update_count_then_panic
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  29: std::rt::lang_start
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/rt.rs:64
  30: build_script_build::main

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `wasmtime-wasi-c v0.0.0 (/Users/acrichton/code/wasmtime/wasmtime-wasi-c)`
process didn't exit successfully: `/Users/acrichton/code/wasmtime/target/debug/build/wasmtime-wasi-c-7bc72320cc86d3de/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/Users/acrichton/code/wasmtime/wasmtime-wasi-c/sandboxed-system-primitives" "-DCMAKE_INSTALL_PREFIX=/Users/acrichton/code/wasmtime/target/debug/build/wasmtime-wasi-c-b62fa5d4cb1a9894/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/acrichton/code/wasmtime/target/debug/build/wasmtime-wasi-c-b62fa5d4cb1a9894/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--"
[100%] Built target SandboxedSystemPrimitives
Install the project...
-- Install configuration: "Debug"
-- Installing: /Users/acrichton/code/wasmtime/target/debug/build/wasmtime-wasi-c-b62fa5d4cb1a9894/out/./libSandboxedSystemPrimitives.a
cargo:root=/Users/acrichton/code/wasmtime/target/debug/build/wasmtime-wasi-c-b62fa5d4cb1a9894/out
cargo:rustc-link-search=native=/Users/acrichton/code/wasmtime/target/debug/build/wasmtime-wasi-c-b62fa5d4cb1a9894/out
cargo:rustc-link-lib=static=SandboxedSystemPrimitives

--- stderr
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:308
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:49
   9: alloc::slice::merge_sort::collapse
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/macros.rs:12
  10: clang_sys::load_manually::build::common::search_libclang_directories
             at /Users/acrichton/code/wasmtime/target/debug/build/clang-sys-c99eebbe3167a4ea/out/common.rs:120
  11: clang_sys::load_manually::build::dynamic::search_libclang_directories
             at /Users/acrichton/code/wasmtime/target/debug/build/clang-sys-c99eebbe3167a4ea/out/dynamic.rs:132
  12: clang_sys::load_manually::build::dynamic::find
             at /Users/acrichton/code/wasmtime/target/debug/build/clang-sys-c99eebbe3167a4ea/out/dynamic.rs:159
  13: clang_sys::clang_HTMLTagComment_getTagName::{{closure}}
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.0/src/link.rs:128
  14: clang_sys::load_manually::{{closure}}
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.0/src/link.rs:157
  15: core::ops::function::FnOnce::call_once
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.49.2/src/lib.rs:1688
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/ops/function.rs:231
  16: alloc::raw_vec::alloc_guard
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0/src/inline_lazy.rs:28
  17: std::sync::once::Once::is_completed
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/sync/once.rs:220
  18: std::sync::once::Once::call_once::{{closure}}
             at src/libstd/sync/once.rs:387
  19: std::sync::once::Once::is_completed
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/sync/once.rs:220
  20: bindgen::CodegenConfig::contains
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0/src/inline_lazy.rs:27
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.49.2/<::lazy_static::__lazy_static_internal macros>:12
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.49.2/<::lazy_static::__lazy_static_internal macros>:13
  21: bindgen::ensure_libclang_is_loaded
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.49.2/src/lib.rs:1695
  22: bindgen::Bindings::generate
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.49.2/src/lib.rs:1710
  23: bindgen::args_are_cpp::{{closure}}
             at /Users/acrichton/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.49.2/src/lib.rs:1208
  24: build_script_build::main
             at wasmtime-wasi-c/build.rs:31
  25: std::rt::lang_start::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/rt.rs:64
  26: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  27: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:87
  28: std::panicking::update_count_then_panic
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  29: std::rt::lang_start
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/rt.rs:64
  30: build_script_build::main
```

</details>

It looks like the bad error message was in a file that was generated by the build script in this crate? I couldn't quite track down where the generated code was coming from, but I figured this might ring a bell for you! 

I realize that this is a somewhat vague issue, so I can try to help give more information if necessary!

**Comment by alexcrichton** [comment]
cc @joshpeterson

**Comment by KyleMayes** [comment]
If executing `llvm-config` results in a non-zero exit code, the following Cargo warnings are now printed (instead of panicking from unwrapping an empty `Option`).

The below is what you would see using the aborting `llvm-config` from your example.

```
warning: couldn't execute `/home/kyle/Projects/llvm-config --prefix` (exit code: signal: 6)
warning: set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable
```

Sorry for the delay.
